title = "Hoverbear Consulting"
description = "A computer scientist working in open source towards a more hopeful future."
default_language = "en"
base_url = "https://hoverbear.org"
generate_feed = true
feed_filename = "rss.xml"
compile_sass = true
highlight_code = true
build_search_index = true
highlight_theme = "base16-ocean-dark"

taxonomies = [
    { name = "tags", rss = true },
]

[extra]
author = "Ana Hobden"
github = "hoverbear"
twitter = "a_hoverbear"
menu = [
    { title = "Home", url = "/" },
    #{ title = "Blog", url = "/blog" },
    { title = "Consulting", url = "/consulting" },
    { title = "About", url = "/about" },
    { title = "Tags", url = "/tags" },
]

[extra.cover]
path = "cover.jpg"
photographer = "Kobi Li"
source = "https://unsplash.com/photos/-N0cgDSF_MI"

[extra.logo]
path = "logo.svg"
artist = "Lisa Dentz"
source = "https://www.lisadentz.com/"
